/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { axiosInstance } from '../axios-instance';
export interface CommentModel {
  id?: number;
  userId?: string;
  comment?: string;
  ontologyIRI?: string;
  conceptIRI?: string;
  postedTime?: string;
}

export type ConceptMetadataModelConceptType =
  (typeof ConceptMetadataModelConceptType)[keyof typeof ConceptMetadataModelConceptType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConceptMetadataModelConceptType = {
  TRIDA: 'TRIDA',
  VLASTNOST: 'VLASTNOST',
  VZTAH: 'VZTAH',
} as const;

export interface ConceptMetadataModel {
  id?: number;
  slug?: string;
  conceptType?: ConceptMetadataModelConceptType;
  conceptIri?: string;
  graphName?: string;
  conceptName?: string;
  user?: UserModel;
  isPublished?: boolean;
  inTezaurus?: boolean;
  comments?: CommentModel[];
  createdAt?: string;
  updatedAt?: string;
}

export interface OntologyMetadataModel {
  id?: number;
  slug?: string;
  graphName?: string;
  name?: string;
  user?: UserModel;
  isPublished?: boolean;
  comments?: CommentModel[];
  popis?: string;
  concepts?: ConceptMetadataModel[];
  createdAt?: string;
  updatedAt?: string;
}

export interface UserModel {
  userId?: string;
}

export interface ApiResponseDtoValidationReport {
  data?: ValidationReport;
  message?: string;
  success?: boolean;
}

export interface ValidationReport {
  id?: number;
  timestamp?: string;
  results?: ValidationResult[];
  ontologyIri?: string;
}

export type ValidationResultSeverity =
  (typeof ValidationResultSeverity)[keyof typeof ValidationResultSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationResultSeverity = {
  ERROR: 'ERROR',
  WARNING: 'WARNING',
  INFO: 'INFO',
} as const;

export interface ValidationResult {
  severity?: ValidationResultSeverity;
  message?: string;
  ruleName?: string;
  focusNodeUri?: string;
  resultPathUri?: string;
  value?: string;
  error?: boolean;
  warning?: boolean;
  info?: boolean;
  focusNodeName?: string;
}

export interface CatalogRequestDto {
  ontologyMetadata?: OntologyMetadataModel;
  validationReport?: ValidationReportDto;
}

export interface ValidationReportDto {
  results?: ValidationResult[];
  timestamp?: string;
  ontologyIri?: string;
  id?: number;
}

export interface ApiResponseDtoCatalogRecordDto {
  data?: CatalogRecordDto;
  message?: string;
  success?: boolean;
}

export type CatalogRecordDtoPopis = { [key: string]: string };

export type CatalogRecordDtoNázev = { [key: string]: string };

export type CatalogRecordDtoKlíčovéSlovo = { [key: string]: string[] };

export type CatalogRecordDtoKontaktníBod = {
  [key: string]: { [key: string]: unknown };
};

export interface CatalogRecordDto {
  iri?: string;
  typ?: string;
  popis?: CatalogRecordDtoPopis;
  specifikace?: string[];
  distribuce?: DistribuceDto[];
  '@context'?: string;
  název?: CatalogRecordDtoNázev;
  prvek_rúian?: string[];
  geografické_území?: string[];
  prostorové_pokrytí?: string[];
  klíčové_slovo?: CatalogRecordDtoKlíčovéSlovo;
  periodicita_aktualizace?: string;
  téma?: string[];
  koncept_euroVoc?: string[];
  kontaktní_bod?: CatalogRecordDtoKontaktníBod;
}

export interface DistribuceDto {
  typ?: string;
  podmínky_užití?: PodminkyUzitiDto;
  soubor_ke_stažení?: string;
  přístupové_url?: string;
  typ_média?: string;
  formát?: string;
  schéma?: string;
}

export interface PodminkyUzitiDto {
  typ?: string;
  autorské_dílo?: string;
  databáze_jako_autorské_dílo?: string;
  databáze_chráněná_zvláštními_právy?: string;
  osobní_údaje?: string;
}

export interface ApiResponseDtoOntologyMetadataModel {
  data?: OntologyMetadataModel;
  message?: string;
  success?: boolean;
}

export type DescriptionModelDescription = { [key: string]: string };

export interface DescriptionModel {
  description?: DescriptionModelDescription;
}

export type NameModelName = { [key: string]: string };

export interface NameModel {
  name?: NameModelName;
}

export interface OntologyCreateModel {
  namespace?: string;
  nameModel: NameModel;
  descriptionModel: DescriptionModel;
}

export type AltNameModelAltName = { [key: string]: string };

export interface AltNameModel {
  altName?: AltNameModelAltName;
}

export type ClassConceptModelAllOf = {
  type?: string;
  agendaCode?: string;
  agendaSystemCode?: string;
  contentType?: string;
  acquisitionMethod?: string;
  sharingMethod?: string[];
  isInPPDF?: boolean;
  isPublic?: boolean;
  privacyProvisions?: string[];
  broaderConcept?: string[];
  codeListDataset?: string;
};

export type ClassConceptModel = ConceptCreateModel & ClassConceptModelAllOf;

export type ConceptCreateModelConceptTypeEnum =
  (typeof ConceptCreateModelConceptTypeEnum)[keyof typeof ConceptCreateModelConceptTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConceptCreateModelConceptTypeEnum = {
  TRIDA: 'TRIDA',
  VLASTNOST: 'VLASTNOST',
  VZTAH: 'VZTAH',
} as const;

export interface ConceptCreateModel {
  ontologyGraphName: string;
  conceptType: string;
  namespace?: string;
  nameModel: NameModel;
  identifier?: string;
  altNameModel?: AltNameModel;
  descriptionModel?: DescriptionModel;
  definitionModel?: DefinitionModel;
  definingNonLegalSource?: string[];
  definingLegalSource?: string[];
  relatedNonLegalSource?: string[];
  relatedLegalSource?: string[];
  exactMatch?: string[];
  inTezaurus?: boolean;
  conceptTypeEnum?: ConceptCreateModelConceptTypeEnum;
}

export type DefinitionModelDefinition = { [key: string]: string };

export interface DefinitionModel {
  definition?: DefinitionModelDefinition;
}

export type PropertyConceptModelAllOf = {
  dataType?: string;
  domain?: string;
  superProperty?: string[];
  isInPPDF?: boolean;
  agendaCode?: string;
  agendaSystemCode?: string;
  isPublic?: boolean;
  privacyProvisions?: string[];
  sharingMethod?: string[];
  acquisitionMethod?: string;
  contentType?: string;
  codeListDataset?: string;
};

export type PropertyConceptModel = ConceptCreateModel &
  PropertyConceptModelAllOf;

export type RelationshipConceptModelAllOf = {
  domain?: string;
  range?: string;
  superRelation?: string[];
  agendaCode?: string;
  agendaSystemCode?: string;
  contentType?: string;
  acquisitionMethod?: string;
  sharingMethod?: string[];
  isInPPDF?: boolean;
  isPublic?: boolean;
  privacyProvisions?: string[];
  codeListDataset?: string;
};

export type RelationshipConceptModel = ConceptCreateModel &
  RelationshipConceptModelAllOf;

export interface ApiResponseDtoConceptMetadataModel {
  data?: ConceptMetadataModel;
  message?: string;
  success?: boolean;
}

export interface CommentCreateModel {
  ontologyIRI?: string;
  conceptIRI?: string;
  comment?: string;
}

export interface ApiResponseDtoCommentModel {
  data?: CommentModel;
  message?: string;
  success?: boolean;
}

export interface OntologyEditModel {
  nameModel?: NameModel;
  descriptionModel?: DescriptionModel;
}

export type ClassConceptEditModelAllOf = {
  type?: string;
  agendaCode?: string;
  agendaSystemCode?: string;
  contentType?: string;
  acquisitionMethod?: string;
  sharingMethod?: string[];
  isPublic?: boolean;
  privacyProvisions?: string[];
  broaderConcept?: string[];
  isInPPDF?: boolean;
  codeListDataset?: string;
};

export type ClassConceptEditModel = ConceptEditModel &
  ClassConceptEditModelAllOf;

export type ConceptEditModelConceptTypeEnum =
  (typeof ConceptEditModelConceptTypeEnum)[keyof typeof ConceptEditModelConceptTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConceptEditModelConceptTypeEnum = {
  TRIDA: 'TRIDA',
  VLASTNOST: 'VLASTNOST',
  VZTAH: 'VZTAH',
} as const;

export interface ConceptEditModel {
  conceptType: string;
  namespace?: string;
  nameModel?: NameModel;
  identifier?: string;
  altNameModel?: AltNameModel;
  descriptionModel?: DescriptionModel;
  definitionModel?: DefinitionModel;
  definingNonLegalSource?: string[];
  definingLegalSource?: string[];
  relatedNonLegalSource?: string[];
  relatedLegalSource?: string[];
  exactMatch?: string[];
  inTezaurus?: boolean;
  conceptTypeEnum?: ConceptEditModelConceptTypeEnum;
}

export type PropertyConceptEditModelAllOf = {
  dataType?: string;
  domain?: string;
  superProperty?: string[];
  isInPPDF?: boolean;
  agendaCode?: string;
  agendaSystemCode?: string;
  isPublic?: boolean;
  privacyProvisions?: string[];
  sharingMethod?: string[];
  acquisitionMethod?: string;
  contentType?: string;
  codeListDataset?: string;
};

export type PropertyConceptEditModel = ConceptEditModel &
  PropertyConceptEditModelAllOf;

export type RelationshipConceptEditModelAllOf = {
  domain?: string;
  range?: string;
  superRelation?: string[];
  isInPPDF?: boolean;
  agendaCode?: string;
  agendaSystemCode?: string;
  isPublic?: boolean;
  privacyProvisions?: string[];
  sharingMethod?: string[];
  acquisitionMethod?: string;
  contentType?: string;
  codeListDataset?: string;
};

export type RelationshipConceptEditModel = ConceptEditModel &
  RelationshipConceptEditModelAllOf;

export interface ApiResponseDtoUserInfoDto {
  data?: UserInfoDto;
  message?: string;
  success?: boolean;
}

export interface UserInfoDto {
  userId?: string;
  displayName?: string;
  roles?: string[];
  admin?: boolean;
}

export type ConceptDetailModelNázev = { [key: string]: string };

export type ConceptDetailModelAlternativníNázev = {
  [key: string]: { [key: string]: unknown };
};

export type ConceptDetailModelDefinice = { [key: string]: string };

export type ConceptDetailModelPopis = { [key: string]: string };

export type ConceptDetailModelDefinujícíNelegislativníZdrojItem = {
  [key: string]: { [key: string]: unknown };
};

export type ConceptDetailModelSouvisejícíNelegislativníZdrojItem = {
  [key: string]: { [key: string]: unknown };
};

export interface ConceptDetailModel {
  conceptProperties?: ConceptPropertiesModel[];
  conceptRelationships?: ConceptRelationshipsModel[];
  iri?: string;
  typ?: string[];
  název?: ConceptDetailModelNázev;
  'alternativní-název'?: ConceptDetailModelAlternativníNázev;
  definice?: ConceptDetailModelDefinice;
  popis?: ConceptDetailModelPopis;
  identifikátor?: string;
  'ekvivalentní-pojem'?: string[];
  'definiční-obor'?: string;
  'obor-hodnot'?: string;
  'nadřazená-třída'?: string[];
  'nadřazený-vztah'?: string[];
  'nadřazená-vlastnost'?: string[];
  'definující-ustanovení-právního-předpisu'?: string[];
  'související-ustanovení-právního-předpisu'?: string[];
  'definující-nelegislativní-zdroj'?: ConceptDetailModelDefinujícíNelegislativníZdrojItem[];
  'související-nelegislativní-zdroj'?: ConceptDetailModelSouvisejícíNelegislativníZdrojItem[];
  'způsob-sdílení-údaje'?: string[];
  'způsob-získání-údaje'?: string;
  'typ-obsahu-údaje'?: string;
  'je-ppdf'?: boolean;
  'agendový-informační-systém'?: string;
  agenda?: string;
  'ustanovení-dokládající-neveřejnost-údaje'?: string[];
}

export interface ConceptPropertiesModel {
  name?: string;
  slug?: string;
}

export interface ConceptRelationshipsModel {
  name?: string;
  slug?: string;
}

export type GetOntologyDtoPublishedConceptDeviations = {
  [key: string]: PublishedConceptDeviationModel;
};

export interface GetOntologyDto {
  ontologyMetadata?: OntologyMetadataModel;
  ontologyDetail?: OntologyDetailModel;
  conceptMetadataModelList?: ConceptMetadataModel[];
  publishedOntologyDeviationModel?: PublishedOntologyDeviationModel;
  publishedConceptDeviations?: GetOntologyDtoPublishedConceptDeviations;
}

export type OntologyDetailModelNázev = { [key: string]: string };

export type OntologyDetailModelPopis = { [key: string]: string };

export interface OntologyDetailModel {
  '@context'?: string;
  iri?: string;
  typ?: string[];
  název?: OntologyDetailModelNázev;
  popis?: OntologyDetailModelPopis;
  'časový-okamžik-vytvoření'?: string;
  'časový-okamžik-poslední-změny'?: string;
  pojmy?: ConceptDetailModel[];
}

export interface PropertyDeviationBoolean {
  localValue?: boolean;
  publishedValue?: boolean;
  different?: boolean;
}

export type PropertyDeviationListMapStringObjectLocalValueItem = {
  [key: string]: { [key: string]: unknown };
};

export type PropertyDeviationListMapStringObjectPublishedValueItem = {
  [key: string]: { [key: string]: unknown };
};

export interface PropertyDeviationListMapStringObject {
  localValue?: PropertyDeviationListMapStringObjectLocalValueItem[];
  publishedValue?: PropertyDeviationListMapStringObjectPublishedValueItem[];
  different?: boolean;
}

export interface PropertyDeviationListString {
  localValue?: string[];
  publishedValue?: string[];
  different?: boolean;
}

export type PropertyDeviationMapStringObjectLocalValue = {
  [key: string]: { [key: string]: unknown };
};

export type PropertyDeviationMapStringObjectPublishedValue = {
  [key: string]: { [key: string]: unknown };
};

export interface PropertyDeviationMapStringObject {
  localValue?: PropertyDeviationMapStringObjectLocalValue;
  publishedValue?: PropertyDeviationMapStringObjectPublishedValue;
  different?: boolean;
}

export type PropertyDeviationMapStringStringLocalValue = {
  [key: string]: string;
};

export type PropertyDeviationMapStringStringPublishedValue = {
  [key: string]: string;
};

export interface PropertyDeviationMapStringString {
  localValue?: PropertyDeviationMapStringStringLocalValue;
  publishedValue?: PropertyDeviationMapStringStringPublishedValue;
  different?: boolean;
}

export interface PropertyDeviationString {
  localValue?: string;
  publishedValue?: string;
  different?: boolean;
}

export type PublishedConceptDeviationModelStatus =
  (typeof PublishedConceptDeviationModelStatus)[keyof typeof PublishedConceptDeviationModelStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublishedConceptDeviationModelStatus = {
  NO_DEVIATION: 'NO_DEVIATION',
  HAS_DEVIATIONS: 'HAS_DEVIATIONS',
  ENDPOINT_UNAVAILABLE: 'ENDPOINT_UNAVAILABLE',
  CONCEPT_NOT_FOUND_IN_NKD: 'CONCEPT_NOT_FOUND_IN_NKD',
  QUERY_ERROR: 'QUERY_ERROR',
} as const;

export interface PublishedConceptDeviationModel {
  status?: PublishedConceptDeviationModelStatus;
  errorMessage?: string;
  typ?: PropertyDeviationListString;
  název?: PropertyDeviationMapStringString;
  'alternativní-název'?: PropertyDeviationMapStringObject;
  definice?: PropertyDeviationMapStringString;
  popis?: PropertyDeviationMapStringString;
  identifikátor?: PropertyDeviationString;
  'nadřazená-třída'?: PropertyDeviationListString;
  'nadřazený-vztah'?: PropertyDeviationListString;
  'nadřazená-vlastnost'?: PropertyDeviationListString;
  'definiční-obor'?: PropertyDeviationString;
  'obor-hodnot'?: PropertyDeviationString;
  'ekvivalentní-pojem'?: PropertyDeviationListString;
  'definující-ustanovení-právního-předpisu'?: PropertyDeviationListString;
  'související-ustanovení-právního-předpisu'?: PropertyDeviationListString;
  'definující-nelegislativní-zdroj'?: PropertyDeviationListMapStringObject;
  'související-nelegislativní-zdroj'?: PropertyDeviationListMapStringObject;
  'způsob-sdílení-údajů'?: PropertyDeviationListString;
  'způsob-získání-údajů'?: PropertyDeviationString;
  'typ-obsahu-údajů'?: PropertyDeviationString;
  'je-ppdf'?: PropertyDeviationBoolean;
  ais?: PropertyDeviationString;
  agenda?: PropertyDeviationString;
  'ustanovení-dokládající-neveřejnost-údaje'?: PropertyDeviationListString;
}

export type PublishedOntologyDeviationModelStatus =
  (typeof PublishedOntologyDeviationModelStatus)[keyof typeof PublishedOntologyDeviationModelStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublishedOntologyDeviationModelStatus = {
  NO_DEVIATION: 'NO_DEVIATION',
  HAS_DEVIATIONS: 'HAS_DEVIATIONS',
  ENDPOINT_UNAVAILABLE: 'ENDPOINT_UNAVAILABLE',
  CONCEPT_NOT_FOUND_IN_NKD: 'CONCEPT_NOT_FOUND_IN_NKD',
  QUERY_ERROR: 'QUERY_ERROR',
} as const;

export interface PublishedOntologyDeviationModel {
  status?: PublishedOntologyDeviationModelStatus;
  errorMessage?: string;
  typ?: PropertyDeviationListString;
  název?: PropertyDeviationMapStringString;
  popis?: PropertyDeviationMapStringString;
}

export interface ApiResponseDtoListOntologyMetadataModel {
  data?: OntologyMetadataModel[];
  message?: string;
  success?: boolean;
}

export interface GetConceptDto {
  conceptMetadata?: ConceptMetadataModel;
  conceptDetail?: ConceptDetailModel;
  publishedConceptDeviationModel?: PublishedConceptDeviationModel;
}

export interface ApiResponseDtoListConceptMetadataModel {
  data?: ConceptMetadataModel[];
  message?: string;
  success?: boolean;
}

export type ApiResponseDtoVoidData = { [key: string]: unknown };

export interface ApiResponseDtoVoid {
  data?: ApiResponseDtoVoidData;
  message?: string;
  success?: boolean;
}

export type UploadFromFileParams = {
  providedName?: string;
};

export type UploadFromFileBody = {
  file?: Blob;
};

export type CreateConceptBody =
  | ClassConceptModel
  | PropertyConceptModel
  | RelationshipConceptModel;

export type EditConceptBody =
  | ClassConceptEditModel
  | PropertyConceptEditModel
  | RelationshipConceptEditModel;

export type DownloadFileParams = {
  format: string;
};

export type GetOntologyListParams = {
  userId?: string;
  isPublished?: boolean;
  slugs?: string[];
};

export type GetConceptListParams = {
  userId?: string;
  isPublished?: boolean;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Spustí validaci slovníku proti pravidlům SHACL/SKOS prostřednictvím externí validační služby. Výsledky validace jsou uloženy do databáze. Vyžaduje oprávnění vlastníka nebo administrátora.
 * @summary Validace slovníku
 */
export const validateOntology = (
  slug: string,
  ontologyMetadataModel: OntologyMetadataModel,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoValidationReport>(
    {
      url: `/api/ontology/${slug}/validate`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: ontologyMetadataModel,
      signal,
    },
    options,
  );
};

export const getValidateOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateOntology>>,
    TError,
    { slug: string; data: OntologyMetadataModel },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateOntology>>,
  TError,
  { slug: string; data: OntologyMetadataModel },
  TContext
> => {
  const mutationKey = ['validateOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateOntology>>,
    { slug: string; data: OntologyMetadataModel }
  > = (props) => {
    const { slug, data } = props ?? {};

    return validateOntology(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateOntology>>
>;
export type ValidateOntologyMutationBody = OntologyMetadataModel;
export type ValidateOntologyMutationError = unknown;

/**
 * @summary Validace slovníku
 */
export const useValidateOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validateOntology>>,
      TError,
      { slug: string; data: OntologyMetadataModel },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof validateOntology>>,
  TError,
  { slug: string; data: OntologyMetadataModel },
  TContext
> => {
  const mutationOptions = getValidateOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Vyžádá katalogizační záznam slovníku z validační služby na základě RDF dat a výsledků validace. Vyžaduje oprávnění vlastníka nebo administrátora.
 * @summary Žádost o katalogizační záznam
 */
export const requestCatalogRecord = (
  slug: string,
  catalogRequestDto: CatalogRequestDto,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoCatalogRecordDto>(
    {
      url: `/api/ontology/${slug}/catalog-record`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: catalogRequestDto,
      signal,
    },
    options,
  );
};

export const getRequestCatalogRecordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestCatalogRecord>>,
    TError,
    { slug: string; data: CatalogRequestDto },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestCatalogRecord>>,
  TError,
  { slug: string; data: CatalogRequestDto },
  TContext
> => {
  const mutationKey = ['requestCatalogRecord'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestCatalogRecord>>,
    { slug: string; data: CatalogRequestDto }
  > = (props) => {
    const { slug, data } = props ?? {};

    return requestCatalogRecord(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestCatalogRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestCatalogRecord>>
>;
export type RequestCatalogRecordMutationBody = CatalogRequestDto;
export type RequestCatalogRecordMutationError = unknown;

/**
 * @summary Žádost o katalogizační záznam
 */
export const useRequestCatalogRecord = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestCatalogRecord>>,
      TError,
      { slug: string; data: CatalogRequestDto },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestCatalogRecord>>,
  TError,
  { slug: string; data: CatalogRequestDto },
  TContext
> => {
  const mutationOptions = getRequestCatalogRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Umožňuje nahrát a importovat slovník z RDF souboru (Turtle, JSON-LD). Soubor je validován a uložen do RDF úložiště. Vyžaduje autentizaci.
 * @summary Nahrání slovníku ze souboru
 */
export const uploadFromFile = (
  uploadFromFileBody: UploadFromFileBody,
  params?: UploadFromFileParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (uploadFromFileBody.file !== undefined) {
    formData.append(`file`, uploadFromFileBody.file);
  }

  return axiosInstance<ApiResponseDtoOntologyMetadataModel>(
    {
      url: `/api/ontology/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      params,
      signal,
    },
    options,
  );
};

export const getUploadFromFileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFromFile>>,
    TError,
    { data: UploadFromFileBody; params?: UploadFromFileParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFromFile>>,
  TError,
  { data: UploadFromFileBody; params?: UploadFromFileParams },
  TContext
> => {
  const mutationKey = ['uploadFromFile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFromFile>>,
    { data: UploadFromFileBody; params?: UploadFromFileParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return uploadFromFile(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadFromFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadFromFile>>
>;
export type UploadFromFileMutationBody = UploadFromFileBody;
export type UploadFromFileMutationError = unknown;

/**
 * @summary Nahrání slovníku ze souboru
 */
export const useUploadFromFile = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFromFile>>,
      TError,
      { data: UploadFromFileBody; params?: UploadFromFileParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadFromFile>>,
  TError,
  { data: UploadFromFileBody; params?: UploadFromFileParams },
  TContext
> => {
  const mutationOptions = getUploadFromFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Vytvoří nový prázdný slovník s definovaným jmenným prostorem, názvem a popisem. Slovník je uložen do RDF úložiště. Vyžaduje autentizaci.
 * @summary Vytvoření nového slovníku
 */
export const createOntology = (
  ontologyCreateModel: OntologyCreateModel,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoOntologyMetadataModel>(
    {
      url: `/api/ontology/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: ontologyCreateModel,
      signal,
    },
    options,
  );
};

export const getCreateOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOntology>>,
    TError,
    { data: OntologyCreateModel },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOntology>>,
  TError,
  { data: OntologyCreateModel },
  TContext
> => {
  const mutationKey = ['createOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOntology>>,
    { data: OntologyCreateModel }
  > = (props) => {
    const { data } = props ?? {};

    return createOntology(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOntology>>
>;
export type CreateOntologyMutationBody = OntologyCreateModel;
export type CreateOntologyMutationError = unknown;

/**
 * @summary Vytvoření nového slovníku
 */
export const useCreateOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOntology>>,
      TError,
      { data: OntologyCreateModel },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createOntology>>,
  TError,
  { data: OntologyCreateModel },
  TContext
> => {
  const mutationOptions = getCreateOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Vytvoří nový pojem (třídu, vlastnost nebo vztah) ve slovníku. Podporuje různé typy pojmů podle OFN standardů. Vyžaduje oprávnění vlastníka slovníku nebo administrátora.
 * @summary Vytvoření nového pojmu
 */
export const createConcept = (
  slug: string,
  createConceptBody: CreateConceptBody,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoConceptMetadataModel>(
    {
      url: `/api/concept/${slug}/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createConceptBody,
      signal,
    },
    options,
  );
};

export const getCreateConceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createConcept>>,
    TError,
    { slug: string; data: CreateConceptBody },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createConcept>>,
  TError,
  { slug: string; data: CreateConceptBody },
  TContext
> => {
  const mutationKey = ['createConcept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createConcept>>,
    { slug: string; data: CreateConceptBody }
  > = (props) => {
    const { slug, data } = props ?? {};

    return createConcept(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateConceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof createConcept>>
>;
export type CreateConceptMutationBody = CreateConceptBody;
export type CreateConceptMutationError = unknown;

/**
 * @summary Vytvoření nového pojmu
 */
export const useCreateConcept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createConcept>>,
      TError,
      { slug: string; data: CreateConceptBody },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createConcept>>,
  TError,
  { slug: string; data: CreateConceptBody },
  TContext
> => {
  const mutationOptions = getCreateConceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Umožňuje přidat komentář ke slovníku nebo pojmu. Komentář je identifikován IRI slovníku nebo pojmu. Vyžaduje autentizaci.
 * @summary Přidání komentáře
 */
export const postComment = (
  commentCreateModel: CommentCreateModel,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoCommentModel>(
    {
      url: `/api/comment/post`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: commentCreateModel,
      signal,
    },
    options,
  );
};

export const getPostCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postComment>>,
    TError,
    { data: CommentCreateModel },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postComment>>,
  TError,
  { data: CommentCreateModel },
  TContext
> => {
  const mutationKey = ['postComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postComment>>,
    { data: CommentCreateModel }
  > = (props) => {
    const { data } = props ?? {};

    return postComment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof postComment>>
>;
export type PostCommentMutationBody = CommentCreateModel;
export type PostCommentMutationError = unknown;

/**
 * @summary Přidání komentáře
 */
export const usePostComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postComment>>,
      TError,
      { data: CommentCreateModel },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postComment>>,
  TError,
  { data: CommentCreateModel },
  TContext
> => {
  const mutationOptions = getPostCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Umožňuje upravit metadata slovníku (název, popis) v různých jazycích. Vyžaduje oprávnění vlastníka nebo administrátora.
 * @summary Úprava slovníku
 */
export const editOntology = (
  ontologyId: number,
  ontologyEditModel: OntologyEditModel,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoOntologyMetadataModel>(
    {
      url: `/api/ontology/${ontologyId}/edit`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: ontologyEditModel,
    },
    options,
  );
};

export const getEditOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof editOntology>>,
    TError,
    { ontologyId: number; data: OntologyEditModel },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof editOntology>>,
  TError,
  { ontologyId: number; data: OntologyEditModel },
  TContext
> => {
  const mutationKey = ['editOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof editOntology>>,
    { ontologyId: number; data: OntologyEditModel }
  > = (props) => {
    const { ontologyId, data } = props ?? {};

    return editOntology(ontologyId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EditOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof editOntology>>
>;
export type EditOntologyMutationBody = OntologyEditModel;
export type EditOntologyMutationError = unknown;

/**
 * @summary Úprava slovníku
 */
export const useEditOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof editOntology>>,
      TError,
      { ontologyId: number; data: OntologyEditModel },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof editOntology>>,
  TError,
  { ontologyId: number; data: OntologyEditModel },
  TContext
> => {
  const mutationOptions = getEditOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Umožňuje upravit existující pojem včetně jeho názvu, definice, vztahů a dalších vlastností. Vyžaduje oprávnění vlastníka slovníku nebo administrátora.
 * @summary Úprava pojmu
 */
export const editConcept = (
  conceptId: number,
  editConceptBody: EditConceptBody,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoConceptMetadataModel>(
    {
      url: `/api/concept/${conceptId}/edit`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: editConceptBody,
    },
    options,
  );
};

export const getEditConceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof editConcept>>,
    TError,
    { conceptId: number; data: EditConceptBody },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof editConcept>>,
  TError,
  { conceptId: number; data: EditConceptBody },
  TContext
> => {
  const mutationKey = ['editConcept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof editConcept>>,
    { conceptId: number; data: EditConceptBody }
  > = (props) => {
    const { conceptId, data } = props ?? {};

    return editConcept(conceptId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EditConceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof editConcept>>
>;
export type EditConceptMutationBody = EditConceptBody;
export type EditConceptMutationError = unknown;

/**
 * @summary Úprava pojmu
 */
export const useEditConcept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof editConcept>>,
      TError,
      { conceptId: number; data: EditConceptBody },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof editConcept>>,
  TError,
  { conceptId: number; data: EditConceptBody },
  TContext
> => {
  const mutationOptions = getEditConceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Vrací informace o aktuálně přihlášeném uživateli extrahované z JWT tokenu. Obsahuje ID uživatele, zobrazované jméno, role a příznak administrátora.
 * @summary Získání informací o aktuálním uživateli
 */
export const getCurrentUser = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoUserInfoDto>(
    { url: `/api/user/me`, method: 'GET', signal },
    options,
  );
};

export const getGetCurrentUserQueryKey = () => {
  return [`/api/user/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = unknown;

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Získání informací o aktuálním uživateli
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Vrací kompletní detail slovníku včetně všech pojmů, jejich vztahů a metadat. Obsahuje také informace o odchylkách od publikované verze, pokud existuje. Veřejný endpoint.
 * @summary Detail slovníku
 */
export const getOntologyDetail = (
  slug: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<GetOntologyDto>(
    { url: `/api/ontology/${slug}/detail`, method: 'GET', signal },
    options,
  );
};

export const getGetOntologyDetailQueryKey = (slug?: string) => {
  return [`/api/ontology/${slug}/detail`] as const;
};

export const getGetOntologyDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOntologyDetailQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOntologyDetail>>
  > = ({ signal }) => getOntologyDetail(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOntologyDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOntologyDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOntologyDetail>>
>;
export type GetOntologyDetailQueryError = unknown;

export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOntologyDetail>>,
          TError,
          Awaited<ReturnType<typeof getOntologyDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOntologyDetail>>,
          TError,
          Awaited<ReturnType<typeof getOntologyDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detail slovníku
 */

export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOntologyDetailQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Umožňuje stáhnout slovník v požadovaném formátu (TTL, JSON-LD). Pokud je povoleno omezení stahování slovníků s chybami, slovníky s validačními chybami nelze stáhnout. Veřejný endpoint.
 * @summary Stažení slovníku
 */
export const downloadFile = (
  ontologyId: number,
  params: DownloadFileParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Blob>(
    {
      url: `/api/ontology/${ontologyId}/download`,
      method: 'GET',
      params,
      responseType: 'blob',
      signal,
    },
    options,
  );
};

export const getDownloadFileQueryKey = (
  ontologyId?: number,
  params?: DownloadFileParams,
) => {
  return [
    `/api/ontology/${ontologyId}/download`,
    ...(params ? [params] : []),
  ] as const;
};

export const getDownloadFileQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDownloadFileQueryKey(ontologyId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({
    signal,
  }) => downloadFile(ontologyId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ontologyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DownloadFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadFile>>
>;
export type DownloadFileQueryError = unknown;

export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Stažení slovníku
 */

export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDownloadFileQueryOptions(ontologyId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Vrací seznam slovníků s možností filtrování podle uživatele, stavu publikace nebo konkrétních slugů. Veřejný endpoint.
 * @summary Seznam slovníků
 */
export const getOntologyList = (
  params?: GetOntologyListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoListOntologyMetadataModel>(
    { url: `/api/ontology/list`, method: 'GET', params, signal },
    options,
  );
};

export const getGetOntologyListQueryKey = (params?: GetOntologyListParams) => {
  return [`/api/ontology/list`, ...(params ? [params] : [])] as const;
};

export const getGetOntologyListQueryOptions = <
  TData = Awaited<ReturnType<typeof getOntologyList>>,
  TError = unknown,
>(
  params?: GetOntologyListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOntologyListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOntologyList>>> = ({
    signal,
  }) => getOntologyList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOntologyList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOntologyListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOntologyList>>
>;
export type GetOntologyListQueryError = unknown;

export function useGetOntologyList<
  TData = Awaited<ReturnType<typeof getOntologyList>>,
  TError = unknown,
>(
  params: undefined | GetOntologyListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOntologyList>>,
          TError,
          Awaited<ReturnType<typeof getOntologyList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOntologyList<
  TData = Awaited<ReturnType<typeof getOntologyList>>,
  TError = unknown,
>(
  params?: GetOntologyListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOntologyList>>,
          TError,
          Awaited<ReturnType<typeof getOntologyList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOntologyList<
  TData = Awaited<ReturnType<typeof getOntologyList>>,
  TError = unknown,
>(
  params?: GetOntologyListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Seznam slovníků
 */

export function useGetOntologyList<
  TData = Awaited<ReturnType<typeof getOntologyList>>,
  TError = unknown,
>(
  params?: GetOntologyListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOntologyListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Vrací kompletní detail pojmu včetně všech vlastností, vztahů, definic a dalších metadat. Obsahuje také informace o odchylkách od publikované verze. Veřejný endpoint.
 * @summary Detail pojmu
 */
export const getConceptDetail = (
  slug: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<GetConceptDto>(
    { url: `/api/concept/${slug}/detail`, method: 'GET', signal },
    options,
  );
};

export const getGetConceptDetailQueryKey = (slug?: string) => {
  return [`/api/concept/${slug}/detail`] as const;
};

export const getGetConceptDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getConceptDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConceptDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetConceptDetailQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getConceptDetail>>
  > = ({ signal }) => getConceptDetail(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getConceptDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConceptDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConceptDetail>>
>;
export type GetConceptDetailQueryError = unknown;

export function useGetConceptDetail<
  TData = Awaited<ReturnType<typeof getConceptDetail>>,
  TError = unknown,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConceptDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConceptDetail>>,
          TError,
          Awaited<ReturnType<typeof getConceptDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConceptDetail<
  TData = Awaited<ReturnType<typeof getConceptDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConceptDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConceptDetail>>,
          TError,
          Awaited<ReturnType<typeof getConceptDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConceptDetail<
  TData = Awaited<ReturnType<typeof getConceptDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConceptDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detail pojmu
 */

export function useGetConceptDetail<
  TData = Awaited<ReturnType<typeof getConceptDetail>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getConceptDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetConceptDetailQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Vrací seznam pojmů s možností filtrování podle uživatele nebo stavu publikace. Veřejný endpoint.
 * @summary Seznam pojmů
 */
export const getConceptList = (
  params?: GetConceptListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoListConceptMetadataModel>(
    { url: `/api/concept/list`, method: 'GET', params, signal },
    options,
  );
};

export const getGetConceptListQueryKey = (params?: GetConceptListParams) => {
  return [`/api/concept/list`, ...(params ? [params] : [])] as const;
};

export const getGetConceptListQueryOptions = <
  TData = Awaited<ReturnType<typeof getConceptList>>,
  TError = unknown,
>(
  params?: GetConceptListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConceptList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetConceptListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConceptList>>> = ({
    signal,
  }) => getConceptList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getConceptList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConceptListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConceptList>>
>;
export type GetConceptListQueryError = unknown;

export function useGetConceptList<
  TData = Awaited<ReturnType<typeof getConceptList>>,
  TError = unknown,
>(
  params: undefined | GetConceptListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConceptList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConceptList>>,
          TError,
          Awaited<ReturnType<typeof getConceptList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConceptList<
  TData = Awaited<ReturnType<typeof getConceptList>>,
  TError = unknown,
>(
  params?: GetConceptListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConceptList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConceptList>>,
          TError,
          Awaited<ReturnType<typeof getConceptList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConceptList<
  TData = Awaited<ReturnType<typeof getConceptList>>,
  TError = unknown,
>(
  params?: GetConceptListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConceptList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Seznam pojmů
 */

export function useGetConceptList<
  TData = Awaited<ReturnType<typeof getConceptList>>,
  TError = unknown,
>(
  params?: GetConceptListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConceptList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetConceptListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Smaže slovník a všechna jeho data z RDF úložiště i databáze. Vyžaduje oprávnění vlastníka nebo administrátora.
 * @summary Smazání slovníku
 */
export const deleteOntology = (
  ontologyId: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoVoid>(
    { url: `/api/ontology/${ontologyId}/delete`, method: 'DELETE' },
    options,
  );
};

export const getDeleteOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOntology>>,
    TError,
    { ontologyId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOntology>>,
  TError,
  { ontologyId: number },
  TContext
> => {
  const mutationKey = ['deleteOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOntology>>,
    { ontologyId: number }
  > = (props) => {
    const { ontologyId } = props ?? {};

    return deleteOntology(ontologyId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOntology>>
>;

export type DeleteOntologyMutationError = unknown;

/**
 * @summary Smazání slovníku
 */
export const useDeleteOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteOntology>>,
      TError,
      { ontologyId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteOntology>>,
  TError,
  { ontologyId: number },
  TContext
> => {
  const mutationOptions = getDeleteOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Smaže pojem z RDF úložiště i databáze včetně všech jeho vztahů. Vyžaduje oprávnění vlastníka slovníku nebo administrátora.
 * @summary Smazání pojmu
 */
export const deleteConcept = (
  conceptId: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoVoid>(
    { url: `/api/concept/${conceptId}/delete`, method: 'DELETE' },
    options,
  );
};

export const getDeleteConceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteConcept>>,
    TError,
    { conceptId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteConcept>>,
  TError,
  { conceptId: number },
  TContext
> => {
  const mutationKey = ['deleteConcept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteConcept>>,
    { conceptId: number }
  > = (props) => {
    const { conceptId } = props ?? {};

    return deleteConcept(conceptId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteConceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteConcept>>
>;

export type DeleteConceptMutationError = unknown;

/**
 * @summary Smazání pojmu
 */
export const useDeleteConcept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteConcept>>,
      TError,
      { conceptId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteConcept>>,
  TError,
  { conceptId: number },
  TContext
> => {
  const mutationOptions = getDeleteConceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Smaže komentář z databáze. Vyžaduje oprávnění autora komentáře nebo administrátora.
 * @summary Smazání komentáře
 */
export const deleteComment = (
  commentId: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoVoid>(
    { url: `/api/comment/${commentId}/delete`, method: 'DELETE' },
    options,
  );
};

export const getDeleteCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ['deleteComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteComment>>
>;

export type DeleteCommentMutationError = unknown;

/**
 * @summary Smazání komentáře
 */
export const useDeleteComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationOptions = getDeleteCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
