/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import { axiosInstance } from '../axios-instance';
export interface ApiResponseDtoOntologyMetadataModel {
  data?: OntologyMetadataModel;
  message?: string;
  success?: boolean;
}

export interface CommentModel {
  id?: number;
  userId?: string;
  comment?: string;
  ontologyIRI?: string;
  conceptIRI?: string;
}

export type OntologyMetadataModelOntologyLevel =
  (typeof OntologyMetadataModelOntologyLevel)[keyof typeof OntologyMetadataModelOntologyLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OntologyMetadataModelOntologyLevel = {
  SUBJEKTY_OBJEKTY: 'SUBJEKTY_OBJEKTY',
  VLASTNOSTI: 'VLASTNOSTI',
  VZTAHY: 'VZTAHY',
  RPP: 'RPP',
  DIAGRAM: 'DIAGRAM',
  USTANOVENI_360_2023: 'USTANOVENI_360_2023',
} as const;

export interface OntologyMetadataModel {
  id?: number;
  graphName?: string;
  user?: UserModel;
  isPublished?: boolean;
  validationReport?: ValidationReportDto;
  ontologyLevel?: OntologyMetadataModelOntologyLevel;
  comments?: CommentModel[];
}

export interface UserModel {
  userId?: string;
}

export interface ValidationReportDto {
  id?: number;
  results?: ValidationResult[];
  timestamp?: string;
  ontologyId?: number;
  valid?: boolean;
}

export type ValidationResultSeverity =
  (typeof ValidationResultSeverity)[keyof typeof ValidationResultSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationResultSeverity = {
  ERROR: 'ERROR',
  WARNING: 'WARNING',
  INFO: 'INFO',
} as const;

export interface ValidationResult {
  severity?: ValidationResultSeverity;
  message?: string;
  ruleName?: string;
  focusNodeUri?: string;
  resultPathUri?: string;
  value?: string;
  error?: boolean;
  focusNodeName?: string;
  warning?: boolean;
  info?: boolean;
}

export interface DescriptionModel {
  languageTag?: string;
  description?: string;
}

export interface NameModel {
  languageTag?: string;
  name?: string;
}

export interface OntologyCreateModel {
  namespace?: string;
  nameModel: NameModel;
  descriptionModel: DescriptionModel;
}

export interface AltNameModel {
  languageTag?: string;
  altName?: string;
}

export type ClassConceptModelAllOf = {
  type?: string;
  agendaCode?: string;
  agendaSystemCode?: string;
  contentType?: string;
  acquisitionMethod?: string;
  sharingMethod?: string;
  isInPPDF?: boolean;
  isPublic?: string;
  privacyProvision?: string;
  broaderConcept?: string;
};

export type ClassConceptModel = ConceptCreateModel & ClassConceptModelAllOf;

export type ConceptCreateModelConceptTypeEnum =
  (typeof ConceptCreateModelConceptTypeEnum)[keyof typeof ConceptCreateModelConceptTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConceptCreateModelConceptTypeEnum = {
  TRIDA: 'TRIDA',
  VLASTNOST: 'VLASTNOST',
  VZTAH: 'VZTAH',
} as const;

export interface ConceptCreateModel {
  ontologyGraphName: string;
  conceptType: string;
  namespace?: string;
  nameModel: NameModel;
  identifier?: string;
  altNameModel?: AltNameModel;
  descriptionModel?: DescriptionModel;
  definitionModel?: DefinitionModel;
  definingNonLegalSource?: string;
  definingLegalSource?: string;
  relatedNonLegalSource?: string;
  relatedLegalSource?: string;
  exactMatch?: string;
  inTezaurus?: string;
  conceptTypeEnum?: ConceptCreateModelConceptTypeEnum;
}

export interface DefinitionModel {
  languageTag?: string;
  definition?: string;
}

export type PropertyConceptModelAllOf = {
  dataType?: string;
  domain?: string;
  superProperty?: string;
  isInPPDF?: boolean;
  agendaCode?: string;
  agendaSystemCode?: string;
  isPublic?: string;
  privacyProvision?: string;
  sharingMethod?: string;
  acquisitionMethod?: string;
  contentType?: string;
};

export type PropertyConceptModel = ConceptCreateModel &
  PropertyConceptModelAllOf;

export type RelationshipConceptModelAllOf = {
  domain?: string;
  range?: string;
  superRelation?: string;
  agendaCode?: string;
  agendaSystemCode?: string;
  contentType?: string;
  acquisitionMethod?: string;
  sharingMethod?: string;
  isInPPDF?: boolean;
  isPublic?: string;
  privacyProvision?: string;
};

export type RelationshipConceptModel = ConceptCreateModel &
  RelationshipConceptModelAllOf;

export interface ApiResponseDtoConceptMetadataModel {
  data?: ConceptMetadataModel;
  message?: string;
  success?: boolean;
}

export type ConceptMetadataModelConceptType =
  (typeof ConceptMetadataModelConceptType)[keyof typeof ConceptMetadataModelConceptType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConceptMetadataModelConceptType = {
  TRIDA: 'TRIDA',
  VLASTNOST: 'VLASTNOST',
  VZTAH: 'VZTAH',
} as const;

export interface ConceptMetadataModel {
  id?: number;
  conceptType?: ConceptMetadataModelConceptType;
  conceptIri?: string;
  graphName?: string;
  conceptName?: string;
  user?: UserModel;
  isPublished?: boolean;
  inTezaurus?: string;
  validationReport?: ValidationReportDto;
  comments?: CommentModel[];
}

export interface CommentCreateModel {
  ontologyIRI?: string;
  conceptIRI?: string;
  comment?: string;
}

export interface ApiResponseDtoCommentModel {
  data?: CommentModel;
  message?: string;
  success?: boolean;
}

export interface OntologyEditModel {
  ontologyIRI?: string;
  nameModel?: NameModel;
  descriptionModel?: DescriptionModel;
}

export type ClassConceptEditModelAllOf = {
  type?: string;
  agendaCode?: string;
  agendaSystemCode?: string;
  contentType?: string;
  acquisitionMethod?: string;
  sharingMethod?: string;
  isPublic?: string;
  privacyProvision?: string;
  broaderConcept?: string;
};

export type ClassConceptEditModel = ConceptEditModel &
  ClassConceptEditModelAllOf;

export type ConceptEditModelConceptTypeEnum =
  (typeof ConceptEditModelConceptTypeEnum)[keyof typeof ConceptEditModelConceptTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConceptEditModelConceptTypeEnum = {
  TRIDA: 'TRIDA',
  VLASTNOST: 'VLASTNOST',
  VZTAH: 'VZTAH',
} as const;

export interface ConceptEditModel {
  conceptIRI: string;
  conceptType: string;
  namespace?: string;
  nameModel?: NameModel;
  identifier?: string;
  altNameModel?: AltNameModel;
  descriptionModel?: DescriptionModel;
  definitionModel?: DefinitionModel;
  definingNonLegalSource?: string;
  definingLegalSource?: string;
  relatedNonLegalSource?: string;
  relatedLegalSource?: string;
  exactMatch?: string;
  inTezaurus?: string;
  conceptTypeEnum?: ConceptEditModelConceptTypeEnum;
}

export type PropertyConceptEditModelAllOf = {
  dataType?: string;
  domain?: string;
  superProperty?: string;
  isInPPDF?: boolean;
  agendaCode?: string;
  agendaSystemCode?: string;
  isPublic?: string;
  privacyProvision?: string;
  sharingMethod?: string;
  acquisitionMethod?: string;
  contentType?: string;
};

export type PropertyConceptEditModel = ConceptEditModel &
  PropertyConceptEditModelAllOf;

export type RelationshipConceptEditModelAllOf = {
  domain?: string;
  range?: string;
  superRelation?: string;
  isInPPDF?: boolean;
  agendaCode?: string;
  agendaSystemCode?: string;
  isPublic?: string;
  privacyProvision?: string;
  sharingMethod?: string;
  acquisitionMethod?: string;
  contentType?: string;
};

export type RelationshipConceptEditModel = ConceptEditModel &
  RelationshipConceptEditModelAllOf;

export type ConceptDetailModelNázev = {
  [key: string]: { [key: string]: unknown };
};

export type ConceptDetailModelAlternativníNázev = {
  [key: string]: { [key: string]: unknown };
};

export type ConceptDetailModelDefinice = {
  [key: string]: { [key: string]: unknown };
};

export type ConceptDetailModelPopis = {
  [key: string]: { [key: string]: unknown };
};

export type ConceptDetailModelEkvivalentníPojemItem = {
  [key: string]: { [key: string]: unknown };
};

export interface ConceptDetailModel {
  iri?: string;
  typ?: string[];
  název?: ConceptDetailModelNázev;
  'alternativní-název'?: ConceptDetailModelAlternativníNázev;
  definice?: ConceptDetailModelDefinice;
  popis?: ConceptDetailModelPopis;
  identifikátor?: string[];
  'ekvivalentní-pojem'?: ConceptDetailModelEkvivalentníPojemItem[];
  'definiční-obor'?: string;
  'obor-hodnot'?: string;
  'nadřazená-třída'?: string[];
  'nadřazený-vztah'?: string[];
  'nadřazená-vlastnost'?: string[];
  'definující-ustanovení-právního-předpisu'?: string[];
  'související-ustanovení-právního-předpisu'?: string[];
  'definující-nelegislativní-zdroj'?: string[];
  'související-nelegislativní-zdroj'?: string[];
  'způsob-sdílení-údajů'?: string[];
  'způsob-získání-údajů'?: string;
  'typ-obsahu-údajů'?: string;
  'je-ppdf'?: boolean;
  ais?: string;
  agenda?: string;
  'ustanovení-neverejnost'?: string[];
}

export type OntologyDetailModelNázev = { [key: string]: string };

export type OntologyDetailModelPopis = { [key: string]: string };

export interface OntologyDetailModel {
  '@context'?: string;
  iri?: string;
  typ?: string[];
  název?: OntologyDetailModelNázev;
  popis?: OntologyDetailModelPopis;
  'časový-okamžik-vytvoření'?: string;
  'časový-okamžik-poslední-změny'?: string;
  pojmy?: ConceptDetailModel[];
}

export type ApiResponseDtoVoidData = { [key: string]: unknown };

export interface ApiResponseDtoVoid {
  data?: ApiResponseDtoVoidData;
  message?: string;
  success?: boolean;
}

export type UploadFromFileParams = {
  providedName?: string;
  userId: string;
};

export type UploadFromFileBody = {
  file?: Blob;
};

export type CreateOntologyParams = {
  userId: string;
};

export type CreateConceptParams = {
  userId: string;
};

export type CreateConceptBody =
  | ClassConceptModel
  | PropertyConceptModel
  | RelationshipConceptModel;

export type PostCommentParams = {
  userId: string;
};

export type EditConceptParams = {
  userId: string;
};

export type EditConceptBody =
  | ClassConceptEditModel
  | PropertyConceptEditModel
  | RelationshipConceptEditModel;

export type DownloadFileParams = {
  format: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const uploadFromFile = (
  uploadFromFileBody: UploadFromFileBody,
  params: UploadFromFileParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  if (uploadFromFileBody.file !== undefined) {
    formData.append(`file`, uploadFromFileBody.file);
  }

  return axiosInstance<ApiResponseDtoOntologyMetadataModel>(
    {
      url: `/api/ontology/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      params,
      signal,
    },
    options,
  );
};

export const getUploadFromFileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFromFile>>,
    TError,
    { data: UploadFromFileBody; params: UploadFromFileParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFromFile>>,
  TError,
  { data: UploadFromFileBody; params: UploadFromFileParams },
  TContext
> => {
  const mutationKey = ['uploadFromFile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFromFile>>,
    { data: UploadFromFileBody; params: UploadFromFileParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return uploadFromFile(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadFromFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadFromFile>>
>;
export type UploadFromFileMutationBody = UploadFromFileBody;
export type UploadFromFileMutationError = unknown;

export const useUploadFromFile = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFromFile>>,
      TError,
      { data: UploadFromFileBody; params: UploadFromFileParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadFromFile>>,
  TError,
  { data: UploadFromFileBody; params: UploadFromFileParams },
  TContext
> => {
  const mutationOptions = getUploadFromFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const createOntology = (
  ontologyCreateModel: OntologyCreateModel,
  params: CreateOntologyParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoOntologyMetadataModel>(
    {
      url: `/api/ontology/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: ontologyCreateModel,
      params,
      signal,
    },
    options,
  );
};

export const getCreateOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOntology>>,
    TError,
    { data: OntologyCreateModel; params: CreateOntologyParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOntology>>,
  TError,
  { data: OntologyCreateModel; params: CreateOntologyParams },
  TContext
> => {
  const mutationKey = ['createOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOntology>>,
    { data: OntologyCreateModel; params: CreateOntologyParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createOntology(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOntology>>
>;
export type CreateOntologyMutationBody = OntologyCreateModel;
export type CreateOntologyMutationError = unknown;

export const useCreateOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOntology>>,
      TError,
      { data: OntologyCreateModel; params: CreateOntologyParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createOntology>>,
  TError,
  { data: OntologyCreateModel; params: CreateOntologyParams },
  TContext
> => {
  const mutationOptions = getCreateOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const createConcept = (
  createConceptBody: CreateConceptBody,
  params: CreateConceptParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoConceptMetadataModel>(
    {
      url: `/api/concept/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createConceptBody,
      params,
      signal,
    },
    options,
  );
};

export const getCreateConceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createConcept>>,
    TError,
    { data: CreateConceptBody; params: CreateConceptParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createConcept>>,
  TError,
  { data: CreateConceptBody; params: CreateConceptParams },
  TContext
> => {
  const mutationKey = ['createConcept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createConcept>>,
    { data: CreateConceptBody; params: CreateConceptParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createConcept(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateConceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof createConcept>>
>;
export type CreateConceptMutationBody = CreateConceptBody;
export type CreateConceptMutationError = unknown;

export const useCreateConcept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createConcept>>,
      TError,
      { data: CreateConceptBody; params: CreateConceptParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createConcept>>,
  TError,
  { data: CreateConceptBody; params: CreateConceptParams },
  TContext
> => {
  const mutationOptions = getCreateConceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const postComment = (
  commentCreateModel: CommentCreateModel,
  params: PostCommentParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ApiResponseDtoCommentModel>(
    {
      url: `/api/comment/post`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: commentCreateModel,
      params,
      signal,
    },
    options,
  );
};

export const getPostCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postComment>>,
    TError,
    { data: CommentCreateModel; params: PostCommentParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postComment>>,
  TError,
  { data: CommentCreateModel; params: PostCommentParams },
  TContext
> => {
  const mutationKey = ['postComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postComment>>,
    { data: CommentCreateModel; params: PostCommentParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return postComment(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof postComment>>
>;
export type PostCommentMutationBody = CommentCreateModel;
export type PostCommentMutationError = unknown;

export const usePostComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postComment>>,
      TError,
      { data: CommentCreateModel; params: PostCommentParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postComment>>,
  TError,
  { data: CommentCreateModel; params: PostCommentParams },
  TContext
> => {
  const mutationOptions = getPostCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const editOntology = (
  ontologyEditModel: OntologyEditModel,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoOntologyMetadataModel>(
    {
      url: `/api/ontology/edit`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: ontologyEditModel,
    },
    options,
  );
};

export const getEditOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof editOntology>>,
    TError,
    { data: OntologyEditModel },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof editOntology>>,
  TError,
  { data: OntologyEditModel },
  TContext
> => {
  const mutationKey = ['editOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof editOntology>>,
    { data: OntologyEditModel }
  > = (props) => {
    const { data } = props ?? {};

    return editOntology(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EditOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof editOntology>>
>;
export type EditOntologyMutationBody = OntologyEditModel;
export type EditOntologyMutationError = unknown;

export const useEditOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof editOntology>>,
      TError,
      { data: OntologyEditModel },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof editOntology>>,
  TError,
  { data: OntologyEditModel },
  TContext
> => {
  const mutationOptions = getEditOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const editConcept = (
  editConceptBody: EditConceptBody,
  params: EditConceptParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoConceptMetadataModel>(
    {
      url: `/api/concept/edit`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: editConceptBody,
      params,
    },
    options,
  );
};

export const getEditConceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof editConcept>>,
    TError,
    { data: EditConceptBody; params: EditConceptParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof editConcept>>,
  TError,
  { data: EditConceptBody; params: EditConceptParams },
  TContext
> => {
  const mutationKey = ['editConcept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof editConcept>>,
    { data: EditConceptBody; params: EditConceptParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return editConcept(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EditConceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof editConcept>>
>;
export type EditConceptMutationBody = EditConceptBody;
export type EditConceptMutationError = unknown;

export const useEditConcept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof editConcept>>,
      TError,
      { data: EditConceptBody; params: EditConceptParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof editConcept>>,
  TError,
  { data: EditConceptBody; params: EditConceptParams },
  TContext
> => {
  const mutationOptions = getEditConceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const downloadFile = (
  ontologyId: number,
  params: DownloadFileParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Blob>(
    {
      url: `/api/ontology/${ontologyId}/download`,
      method: 'GET',
      params,
      responseType: 'blob',
      signal,
    },
    options,
  );
};

export const getDownloadFileQueryKey = (
  ontologyId?: number,
  params?: DownloadFileParams,
) => {
  return [
    `/api/ontology/${ontologyId}/download`,
    ...(params ? [params] : []),
  ] as const;
};

export const getDownloadFileQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDownloadFileQueryKey(ontologyId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({
    signal,
  }) => downloadFile(ontologyId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ontologyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DownloadFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadFile>>
>;
export type DownloadFileQueryError = unknown;

export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useDownloadFile<
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  ontologyId: number,
  params: DownloadFileParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDownloadFileQueryOptions(ontologyId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getOntologyDetail = (
  ontologyId: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<OntologyDetailModel>(
    { url: `/api/ontology/${ontologyId}/detail`, method: 'GET', signal },
    options,
  );
};

export const getGetOntologyDetailQueryKey = (ontologyId?: number) => {
  return [`/api/ontology/${ontologyId}/detail`] as const;
};

export const getGetOntologyDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  ontologyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOntologyDetailQueryKey(ontologyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOntologyDetail>>
  > = ({ signal }) => getOntologyDetail(ontologyId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ontologyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOntologyDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOntologyDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOntologyDetail>>
>;
export type GetOntologyDetailQueryError = unknown;

export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  ontologyId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOntologyDetail>>,
          TError,
          Awaited<ReturnType<typeof getOntologyDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  ontologyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOntologyDetail>>,
          TError,
          Awaited<ReturnType<typeof getOntologyDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  ontologyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetOntologyDetail<
  TData = Awaited<ReturnType<typeof getOntologyDetail>>,
  TError = unknown,
>(
  ontologyId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOntologyDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOntologyDetailQueryOptions(ontologyId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteOntology = (
  ontologyId: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoVoid>(
    { url: `/api/ontology/${ontologyId}/delete`, method: 'DELETE' },
    options,
  );
};

export const getDeleteOntologyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOntology>>,
    TError,
    { ontologyId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOntology>>,
  TError,
  { ontologyId: number },
  TContext
> => {
  const mutationKey = ['deleteOntology'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOntology>>,
    { ontologyId: number }
  > = (props) => {
    const { ontologyId } = props ?? {};

    return deleteOntology(ontologyId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOntologyMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOntology>>
>;

export type DeleteOntologyMutationError = unknown;

export const useDeleteOntology = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteOntology>>,
      TError,
      { ontologyId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteOntology>>,
  TError,
  { ontologyId: number },
  TContext
> => {
  const mutationOptions = getDeleteOntologyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const deleteConcept = (
  conceptId: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoVoid>(
    { url: `/api/concept/${conceptId}/delete`, method: 'DELETE' },
    options,
  );
};

export const getDeleteConceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteConcept>>,
    TError,
    { conceptId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteConcept>>,
  TError,
  { conceptId: number },
  TContext
> => {
  const mutationKey = ['deleteConcept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteConcept>>,
    { conceptId: number }
  > = (props) => {
    const { conceptId } = props ?? {};

    return deleteConcept(conceptId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteConceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteConcept>>
>;

export type DeleteConceptMutationError = unknown;

export const useDeleteConcept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteConcept>>,
      TError,
      { conceptId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteConcept>>,
  TError,
  { conceptId: number },
  TContext
> => {
  const mutationOptions = getDeleteConceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const deleteComment = (
  commentId: number,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ApiResponseDtoVoid>(
    { url: `/api/comment/${commentId}/delete`, method: 'DELETE' },
    options,
  );
};

export const getDeleteCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteComment>>,
    TError,
    { commentId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationKey = ['deleteComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteComment>>,
    { commentId: number }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteComment>>
>;

export type DeleteCommentMutationError = unknown;

export const useDeleteComment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteComment>>,
      TError,
      { commentId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: number },
  TContext
> => {
  const mutationOptions = getDeleteCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
